version: '3.8'

services:
  lhtt62026-web:
    build: .
    container_name: lhtt62026-web
    restart: unless-stopped
    ports:
      - '127.0.0.1:3001:3000'
    environment:
      - NOCOBASE_BASE_URL=https://lht.gun.hmz.one
      - NOCOBASE_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVOYW1lIjoicm9vdCIsImlhdCI6MTc4MjU0NDIyOSwiZXhwIjozMzM0MDE0NDIyOX0.l-Aru4p4MXyS6teBgmJQKeS2SfhMCUPV3IGAf2zeYWE
      - NEXT_PUBLIC_BASE_URL=https://lhtt62026.apps.agentic.io.vn
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    extra_hosts:
      - "lht.gun.hmz.one:180.93.137.62"
      - "lhtt62026.apps.agentic.io.vn:host-gateway"
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
